- be/.prettierrc
> [J033] 프리티어 형식 추가

- PlanJ/app/src/main/AndroidManifest.xml
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
- PlanJ/app/src/main/res/anim/from_left_to_right.xml
- PlanJ/app/src/main/res/anim/from_right_to_left.xml
- PlanJ/app/src/main/res/layout/fragment_sign_up.xml
- PlanJ/app/src/main/res/navigation/login_nav.xml
- PlanJ/app/src/main/res/values/strings.xml
- README.md
> [K020] 회원가입 ui 구현 및 화면 이동 구현

- PlanJ/.gitignore
- PlanJ/.idea/misc.xml
- PlanJ/app/src/main/res/drawable/ic_drop_arrow.xml
- PlanJ/app/src/main/res/drawable/ic_fail.xml
- PlanJ/app/src/main/res/drawable/ic_repeat.xml
- PlanJ/app/src/main/res/drawable/id_group.xml
- PlanJ/app/src/main/res/layout/item_schedule.xml
> [K026] 일정 카드 UI 구현

- PlanJ/.idea/misc.xml
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/CalendarAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/WeekFragment.kt
- PlanJ/app/src/main/res/layout/activity_main.xml
- PlanJ/app/src/main/res/layout/fragment_today.xml
- PlanJ/app/src/main/res/layout/fragment_week.xml
- PlanJ/app/src/main/res/layout/item_day.xml
- PlanJ/app/src/main/res/values/strings.xml
- PlanJ/app/src/main/res/values/week_array.xml
> [K041] 주간 달력 구현

- be/package-lock.json
- be/package.json
- be/src/auth/user.repository.ts
> [J161] 이메일 중복 가입 방지 구현

- PlanJ/app/build.gradle.kts
- PlanJ/app/src/main/AndroidManifest.xml
- PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/SignUpRequest.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/network/PlanJAPI.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/LoginActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
- PlanJ/app/src/main/res/layout/fragment_sign_up.xml
- PlanJ/gradle/libs.versions.toml
> [K020] 회원가입 네트워크 통신 추가

- be/src/app.module.ts
- be/src/auth/auth.controller.ts
- be/src/auth/auth.service.ts
- be/src/auth/user.repository.ts
- be/src/schedule/schedule.controller.spec.ts
- be/src/schedule/schedule.controller.ts
- be/src/schedule/schedule.module.ts
- be/src/schedule/schedule.service.spec.ts
- be/src/schedule/schedule.service.ts
- 회원가입 성공 시 응답 메시지 body 형식 변경
-  Schedule 모듈 생성, 개발 준비
> [J161] 회원가입 성공 시 응답 메시지 body 형식 변경

- be/src/auth/auth.controller.ts
- be/src/auth/auth.service.ts
- be/src/auth/user.repository.ts
- be/src/main.ts
- be/src/utils/http.response.ts
> [J033] 응답 데이터 통일을 위한 Interface 추가

- be/src/auth/auth.controller.ts
- be/src/auth/auth.service.ts
- be/src/auth/user.repository.ts
> Feat: 회원 탈퇴 기능 구현

- be/src/auth/auth.controller.ts
- be/src/auth/auth.service.ts
- be/src/auth/dto/user-modify.dto.ts
- be/src/auth/user.repository.ts
- be/src/utils/http.response.ts
- conflict resolve
- 회원 정보 수정 구현
- 현재는 닉네임 수정만 가능
> [J033] 회원 정보 수정 구현

- PlanJ/.idea/deploymentTargetDropDown.xml
- PlanJ/app/src/main/AndroidManifest.xml
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapterViewHolder.kt
- PlanJ/app/src/main/res/layout/fragment_today.xml
- PlanJ/app/src/main/res/layout/item_schedule.xml
- PlanJ/app/src/main/res/layout/item_today_schedule.xml
- PlanJ/app/src/main/res/values/strings.xml
- PlanJ/app/src/main/res/xml/item_today_schedule_scene.xml
+ 모션 레이아웃을 사용하니, todayFragment에서 중복된 코드가 전부 삭제되고, 코드가 간결해짐
+ 아직 더미데이터라 날짜별 정렬, 날짜 표시 부분은 아직 구현은 안했습니다.
+ retrofit으로 요청 응답을 할 수 있을 때 ViewModel로 구현할 예정
> [K026] today 화면을 2개의 어댑터로 UI 구현, 모션 레이아웃을 이용해 일정 보이기/숨기기 기능 구현

- PlanJ/app/build.gradle.kts
- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/AppDatabase.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/TypeConverter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Repetition.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayViewModel.kt
- PlanJ/build.gradle.kts
+ TypeConverter로 Repetition, List<User> 컨버터하기
+ Schedule Entity 설정
> [K026] Room 더미데이터 넣기

- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
- PlanJ/app/src/main/res/layout/activity_schedule.xml
- ScheduleViewModel 추가
- 상단바 이전버튼, 완료버튼 리스너 추가
> [K020] 일정 추가 화면 데이터 바인딩 및 클릭 이벤트

- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/TypeConverter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SwipeListener.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/TodayViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/ScheduleViewHolder.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/adapter/SegmentScheduleAdapterViewHolder.kt
- 스와이프 삭제 기능 구현
- undo 클릭 시 다시 해당 일정 복구
> [K026] 일정 스와이프 기능 구현

- be/src/schedule/entity/schedule.entity.ts
- be/src/schedule/entity/schedule.meta.entity.ts
> [J033] schedule entity 작성

- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/schedule.controller.ts
- be/src/schedule/schedule.module.ts
- be/src/schedule/schedule.repository.ts
- be/src/schedule/schedule.service.ts
- 일정 추가 로직 초안 작성 (schedule.meta DB만 존재한다고 가정)
> [J161] 일정 추가 로직 초안 작성

- be/src/auth/entity/user.entity.ts
- be/src/schedule/entity/participant.entity.ts
- be/src/schedule/entity/schedule.meta.entity.ts
- Schedule과 User간 다대다 관계를 Participant 관계를 이용해 일대다로 수정
> [J033] participant.entity.ts 작성

- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
- PlanJ/app/src/main/res/layout/activity_schedule.xml
- PlanJ/app/src/main/res/values/styles.xml
> [K020] 일정추가 UI에서 카테고리 선택 메뉴로 변경

- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/schedule.meta.repository.ts
- be/src/schedule/schedule.module.ts
- be/src/schedule/schedule.repository.ts
- be/src/schedule/schedule.service.ts
- http 요청 시 body 날짜 형식 지정 (2023-11-16T18:00:00)
- ScheduleMeta 테이블과 Schedule 테이블 모두에 데이터가 저장되도록 구현
> [J161] addSchedule() 실행 시 ScheduleMeta 테이블과 Schedule 테이블 모두에 데이터가 저장되도록 구현

- be/package.json
> [J033] 서버용 스크립트 수정

- be/Dockerfile
- be/docker-compose.yml
- be/nginx/Dockerfile
- be/nginx/default.conf
- 서버의 docker에서 사용할 docker-compose.yml 작성
- NestJS, NginX image 생성용 Dockerfile 작성
- NginX configure default.conf 작성
> [J033] Dockerfile, docker-compose.yml 작성

- be/src/category-api/category-api.module.ts
- be/src/schedule-api/schedule-api.module.ts
> [J161] 빌드 오류 수정

- be/src/app.module.ts
- be/src/friend/dto/add-friend.dto.ts
- be/src/friend/entity/friends.entity.ts
- be/src/friend/friend.controller.spec.ts
- be/src/friend/friend.controller.ts
- be/src/friend/friend.module.ts
- be/src/friend/friend.repository.ts
- be/src/friend/friend.service.spec.ts
- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/update-schedule.dto.ts
- be/src/schedule/entity/schedule-location.entity.ts
- be/src/schedule/schedule-location.respository.ts
- be/src/schedule/schedule-location.service.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.module.ts
- 일정 수정 시 위치 정보 추가 기능 구현
- 친구 추가 모듈 생성, 기능 구현 미완성
> [J161] 일정 수정 시 위치 정보 추가 기능 구현, 친구 추가 모듈 생성 

- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/CategoryDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/db/ScheduleDao.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Schedule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/categorydetail/CategoryDetailFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/today/TodayFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
- PlanJ/app/src/main/res/layout/fragment_schedule.xml
- PlanJ/app/src/main/res/navigation/schedule_nav.xml
- PlanJ/app/src/main/res/values/strings.xml
- 일정을 클릭하여 상세 화면 이동시 해당 schedule 객체 전달
- 바인딩 어댑터 문자열 string 리소스로 분리
> [K020] 일정 상세 화면 이동

- be/src/schedule/schedule-location.repository.ts
> [J033] 오타 수정

- be/src/user-api/user-api.controller.ts
- be/src/user-api/user-api.service.ts
- be/src/user/user.service.ts
> [J033] jwt를 이용한 회원 기능 추가

- be/src/user/user.repository.ts
- be/src/user/user.service.ts
- naming rule에 따라 method 이름 변경
> [J033] method 이름 변경

- be/src/auth/auth.service.ts
- be/src/user-api/user-api.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
- be/src/utils/token.decorator.ts
- 헤더에서 JWT를 추출하는 데코레이터 구현
- user module에서 해야 할 내용 작성
> [J033] 헤더에서 jwt를 추출하는 데코레이터 구현

- be/src/category-api/category-api.controller.ts
- be/src/category-api/category-api.module.ts
- be/src/category-api/category-api.service.ts
- be/src/category/category.repository.ts
- be/src/category/dto/add-category.dto.ts
- be/src/category/dto/delete-category.dto.ts
- be/src/category/entity/category.entity.ts
- be/src/config/typeorm.config.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.module.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/dto/delete-schedule.dto.ts
- be/src/schedule/dto/update-schedule.dto.ts
- be/src/schedule/schedule.module.ts
- jwt 토큰 사용으로 controller에 guard를 적용하여 토큰 검증 및 사용자 검증
- 일부 dto에서 userUuid의 검증 삭제
- guard에서 uuid를 추출하지만 반복적으로 다시 service 내부에서 uuid를 추출하는 동작 필요로 guard에서 이를 처리할 방법 강구
> [J033] guard 적용

- be/src/category-api/category-api.controller.ts
- be/src/category-api/category-api.service.ts
- be/src/category/category.repository.ts
- be/src/category/category.service.ts
- be/src/category/dto/add-category.dto.ts
- be/src/category/dto/update-category.dto.ts
- be/src/category/entity/category.entity.ts
- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/entity/schedule-metadata.entity.ts
- be/src/schedule/schedule-location.repository.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/user/user.service.ts
- 카테고리 수정 기능
- 카테고리 별 조회 기능
- Resolve conflict
> [J033] 카테고리 수정, 카테고리 별 일정 조회 기능 추가

- be/src/category-api/category-api.controller.ts
- be/src/category-api/category-api.service.ts
- be/src/category/category.repository.ts
- be/src/category/category.service.ts
- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/dto/schedule.response.ts
- be/src/schedule/schedule-location.repository.ts
- be/src/schedule/schedule-location.service.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
- 기본 카테고리로 조회 기능 구현
- schedule 응답 부분 interface 구현
> [J033] 기본 카테고리 조회 추가

- be/src/friend/entity/friend.entity.ts
- be/src/friend/friend.controller.ts
- be/src/friend/friend.module.ts
- be/src/friend/friend.repository.ts
- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/invite-schedule.dto.ts
- be/src/schedule/entity/participant.entity.ts
- be/src/schedule/entity/schedule-metadata.entity.ts
- be/src/schedule/participate.repository.ts
- be/src/schedule/participate.service.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule.module.ts
- be/src/user/entity/user.entity.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
- 친구 목록 추가 및 조회 기능 구현
- participant 테이블을 추가함으로써 user 테이블과 schedule_metadata 테이블간의 관계를 수정하여 중간에 participant 테이블이 있도록 수정함. 우선 일정 추가를 하면 participant 테이블에 user_id와 metadata_id (엔티티)가 저장되고, author = true로 저장함 (모든 일정은 만든 사람이 author), author = false인 나머지 사람을 초대하는 기능은 내일 구현 예정
> [J161] 친구 목록 추가 및 조회 기능 구현, participant 테이블 추가

- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapterViewHolder.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantDialog.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/SetDialogSize.kt
- PlanJ/app/src/main/res/drawable/ic_done.xml
- PlanJ/app/src/main/res/drawable/ic_not_done.xml
- PlanJ/app/src/main/res/layout/dialog_participants.xml
- PlanJ/app/src/main/res/layout/fragment_schedule.xml
- PlanJ/app/src/main/res/layout/item_participant.xml
- PlanJ/app/src/main/res/values/colors.xml
- PlanJ/app/src/main/res/values/strings.xml
- 참가자 목록 전체보기 클릭 -> 전체 참가자를 볼 수 있는 다이얼로그 추가
- 참가자의 완료 여부에 따라 O/X 표시
- 참가자들의 정보와 완료여부가 어떤 형식으로 들어올지 확정되지않아 Participant 데이터 클래스 추가하여 구현
> [K020] 참가자 목록 전체보기 및 완료 여부 시각적으로 보이도록 구현

- PlanJ/app/build.gradle.kts
- PlanJ/app/src/main/AndroidManifest.xml
- PlanJ/app/src/main/java/com/boostcamp/planj/data/PlanJReceiver.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/di/MainModule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/di/RepositoryModule.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/AlarmRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/BindingAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/AlarmSettingDialog.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/RepetitionSettingDialog.kt
- 알람매니저
- 알람 설정(출발 시간 기준 알람이면 출발 위치에서 도착 위치까지 소요되는 시간을 더 빼주어야 하는데 이 부분이 데이터가 어떻게 넘어올 지 결정되지 않아 빼고 구현했다)
- 알람 취소
- 어플에서 실행한 화면이 없어 연습용으로 실행한 화면을 대신하여 첨부
- 알람이 설정되는지 확인하기 위해 And 브랜치 머지한 후 테스트를 했다. 알람을 설정하면 설정한 시간에 푸시 알림이 뜨는 것을 확인한 후 테스트한 코드는 제거했다.
- 레포지토리를 만드는 것이 과연 적절할까라는 고민만 엄청 한 이번 구현이었다. 알람 설정 관련 파일은 ui 패키지에 두어야 할까 data 패키지에 두어야할까... 구현 자체에서 크게 막힌 부분은 없었는데 역할 분리를 어떻게 해야할 지 고민을 했고, 일단 레포지토리를 만들기는 했지만 아직도 고민은 진행중이다. 
레포지토리를 뷰모델에 주입하지 않고 일반 클래스로 만들어서 뷰모델 안에서 객체를 생성하는 것을 어떨까 하는 생각도 든다.
- cmd창에서 알람 등록 확인하기(윈도우 기준)
`adb_shell_dumpsys_alarm | findstr com.boostcamp.planj`
- 등록된 것이 있는지는 확인할 수 있지만 시간 정보가 나타나있지는 않다.
- [알림만들기](https://developer.android.com/training/notify-user/build-notification?hl=ko)
- [반복 알람 예약](https://developer.android.com/training/scheduling/alarms?hl=ko)
> [K020] 알람 설정

- be/src/user-api/user-api.controller.ts
- be/src/user-api/user-api.service.ts
> [J033] 회원 정보 조회 추가

- be/src/category/category.service.ts
> [J033] 미분류 카테고리에 일정 추가 안되는 문제 해결

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/entity/participant.entity.ts
- be/src/schedule/entity/schedule-metadata.entity.ts
- be/src/schedule/participate.repository.ts
- be/src/schedule/participate.service.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- 이미 초대된 일정을 수정할 때 새롭게 일정이 다시 생성되는 오류를 수정함
> [J161] 사용자 초대 기능 오류 수정

- be/src/schedule/dto/schedule-alarm.dto.ts
- be/src/schedule/dto/update-schedule.dto.ts
- be/src/schedule/entity/schedule-alarm.entity.ts
- be/src/schedule/schedule.module.ts
- be/src/user-api/user-api.controller.ts
> [J033] 의존성으로 인한 오류 해결

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/schedule.response.ts
- be/src/schedule/participate.service.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- 일간, 주간 일정 조회 시 반복 여부, 알람 설정 여부, 참가자 수 및 성공한 참가자 수 응답
> [J161] 일간, 주간 일정 조회 시 반복 여부, 알람 설정 여부, 참가자 수 및 성공한 참가자 수 응답

- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/schedule.service.ts
- 사용자가 일정을 체크했을 때 동작 처리 완료
- 친구 목록 조회 시 profile url 같이 전송
> [J033] 사용자가 일정을 체크할 때 처리 구현

- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/WeekFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/CalendarViewHolder.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/week/adapter/ScheduleSimpleViewHolder.kt
- PlanJ/app/src/main/res/layout/dialog_schedule_result.xml
- PlanJ/app/src/main/res/layout/fragment_week.xml
- PlanJ/app/src/main/res/values/strings.xml
- 다이얼로그 바인딩을 잘못 적은 부분 수정
- 통계 동작 방식 수정
- 주간 XML화면 수정
> [K041] 다이얼로그, 주간화면 수정

- be/Dockerfile
- be/nginx/Dockerfile
- be/nginx/nginx.conf
- be/src/category/category.service.ts
- be/src/category/entity/category.entity.ts
- be/src/friend/entity/friend.entity.ts
- be/src/friend/friend.service.ts
- be/src/guard/auth.guard.ts
- be/src/image/image.service.spec.ts
- be/src/schedule-api/interface/alarmInfo.response.ts
- be/src/schedule-api/interface/location.response.ts
- be/src/schedule-api/interface/participant.response.ts
- be/src/schedule-api/interface/repetition.response.ts
- be/src/schedule-api/interface/schedule-detail.response.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/schedule.response.ts
- be/src/schedule/entity/repetition.entity.ts
- be/src/schedule/entity/schedule-alarm.entity.ts
- be/src/schedule/entity/schedule-location.entity.ts
- be/src/schedule/entity/schedule-metadata.entity.ts
- be/src/schedule/entity/schedule.entity.ts
- be/src/schedule/repetition.service.ts
- be/src/schedule/schedule-alarm.service.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- be/src/user-api/user-api.controller.ts
- be/src/user/entity/user.entity.ts
- be/src/utils/domain/alarm-type.enum.ts
- be/src/utils/domain/cycle-type.enum.ts
- 일정 상세 조회 기능 구현
- 주간, 일간 일정 조회 시 실패했을 경우 참고할 회고 메모 유무 여부 추가
> [J033] 일정 상세 조회 기능 구현

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/repetition.service.ts
UpdateScheduleDto -> RepetitionDto 로 변경
> [J161] updateRepetition 인자 타입 변경

- be/src/user-api/user-api.controller.ts
프로필 이미지 기본으로 변경 요청 메서드 Patch로 변경
> [J033] change method to Patch

- be/src/category/category.service.ts
- 미분류 카테고리의 경우 다른 카테고리의 이름 뜨는 문제 발생 해결
> [J033] 미분류 카테고리 조회 오류 수정

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/check-schedule.response.ts
- be/src/schedule/schedule.service.ts
> [J033] 일정 완료 체크 응답에 속성 추가

- be/.dockerignore
- be/Dockerfile
> [J033] 도커 파일 수정

- be/.dockerignore
- be/src/config/typeorm.config.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/memo.response.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
> [J033] 회고 메모 조회 기능 추가

- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantAdapterViewHolder.kt
- PlanJ/app/src/main/res/layout/item_participant.xml
- checkbox / O / X visibility 관련 변경
> [K020] visibility -> 데이터바인딩으로 변경

- be/src/schedule-api/dto/alarmInfo.response.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/schedule-alarm.dto.ts
- be/src/schedule/dto/schedule-location.dto.ts
- be/src/schedule/entity/schedule-alarm.entity.ts
- be/src/schedule/participate.repository.ts
- be/src/schedule/participate.service.ts
- be/src/schedule/schedule-alarm.service.ts
- be/src/schedule/schedule-location.service.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- be/src/user-api/user-api.controller.ts
> [J033] 업데이트 관련 수정

- be/nest-cli.json
- be/package-lock.json
- be/package.json
- be/src/category-api/category-api.controller.ts
- be/src/category/dto/add-category.dto.ts
- be/src/category/dto/delete-category.dto.ts
- be/src/category/dto/update-category.dto.ts
- be/src/friend/friend.controller.ts
- be/src/main.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule/dto/add-schedule.dto.ts
- be/src/schedule/dto/delete-schedule.dto.ts
- be/src/schedule/dto/repetition.dto.ts
- be/src/schedule/dto/update-schedule.dto.ts
- be/src/user-api/user-api.controller.ts
> [J033] swagger 적용

- be/src/friend/friend.controller.ts
- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- 친구 삭제 기능
- 일정 수정 시 반복 일정이 생기는 오류 수정
> [J033] 친구 삭제 기능 추가, 오류 수정

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/participate.service.ts
- be/src/schedule/schedule-meta.service.ts
- be/src/schedule/schedule.service.ts
- 마지막 반복 일정이 조회 되면 추가 반복 일정 생성
> [J033] 반복 일정 기능 추가

- be/src/schedule/dto/schedule-location.dto.ts
> [J033] dto 오류 수정

- be/src/schedule/schedule.service.ts
>  [J033] 메모 수정

- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/participate.service.ts
> [J033] 공유 일정 삭제 문제 해결

- be/src/friend/friend.controller.ts
- be/src/schedule-api/dto/alarmInfo.response.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/alarm-schedule.response.ts
- be/src/schedule/dto/schedule-alarm.dto.ts
- be/src/schedule/entity/schedule-alarm.entity.ts
- be/src/schedule/schedule-alarm.service.ts
- be/src/schedule/schedule-meta.repository.ts
- be/src/schedule/schedule-meta.service.ts
> [J033] 알람이 설정된 일정 조회 기능 추가

- be/src/category-api/category-api.controller.ts
- be/src/friend/friend.controller.ts
- be/src/friend/friend.service.ts
- be/src/guard/auth.guard.ts
- be/src/main.ts
- be/src/schedule-api/schedule-api.controller.ts
- be/src/schedule/schedule.service.ts
- be/src/user-api/user-api.controller.ts
- be/src/user/user.repository.ts
- be/src/utils/token.decorator.ts
swagger ui에 인증 정보나 응답 example 작성
> [J033] swagger response example 추가

- be/.gitignore
- be/package-lock.json
- be/package.json
- be/src/config/firebase.config.ts
- be/src/friend/friend.module.ts
- be/src/friend/friend.service.ts
- be/src/push/push.module.ts
- be/src/push/push.service.ts
- be/src/schedule-api/schedule-api.module.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/user-api/user-api.controller.ts
- be/src/user-api/user-api.service.ts
- be/src/user/dto/user-login.dto.ts
- be/src/user/entity/user.entity.ts
- be/src/user/user.service.ts
- be/tsconfig.json
> [J033] 푸시 알림 기능 추가

- be/src/user-api/user-api.service.ts
- be/src/user/dto/user-login.dto.ts
- device token이 없어도 로그인 가능 하도록 수정
> [J033] 로그인 오류 수정

- be/src/schedule/schedule-meta.repository.ts
> [J033] 삭제된 일정이 알람 설정시 조회되는 문제 해결

- be/src/friend/friend.service.ts
- be/src/schedule-api/schedule-api.service.ts
> [J033] 친구 추가 메시지 변경

- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanjAlarm.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/CalendarFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/home/HomeViewModel.kt
- PlanJ/app/src/main/res/layout/fragment_home.xml
- MainActivity 실행시 알림 정보를 받아와 알람매니저를 set/delete
- 받아온 정보 로컬에 저장
> [K020] 서버에 저장된 3일간의 알림 정보를 받아와 알람 set, 로컬에 저장

- .gitignore
- be/ecosystem.config.js
- be/nginx/nginx.conf
- be/src/main.ts
> Feat: imply pm2 setting

- be/nginx/nginx.conf
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/dto/schedule.response.ts
- be/src/schedule/schedule-meta.service.ts
> [J033] fix schedule attribute

- be/src/schedule-api/dto/participant.response.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/schedule/schedule.service.ts
> Feat: add attribute on response

- be/src/schedule/participate.repository.ts
> Fix: fix shared schedule

- PlanJ/app/src/main/java/com/boostcamp/planj/data/model/Participant.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/LoginRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepository.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/data/repository/MainRepositoryImpl.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/PlanJReceiver.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignInViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/login/SignUpViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/MainViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/SettingViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/main/friendlist/FriendListViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsFragment.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleParticipantsViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/schedule/ScheduleViewModel.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchViewModel.kt
- PlanJ/app/src/main/res/drawable/ic_chevron_right.xml
- PlanJ/app/src/main/res/layout/activity_search.xml
- PlanJ/app/src/main/res/layout/dialog_fail_write.xml
- PlanJ/app/src/main/res/layout/fragment_setting.xml
- PlanJ/app/src/main/res/menu/toolbar_menu.xml
- PlanJ/app/src/main/res/values/strings.xml
- 설정 화면 
- 푸시알림&스위치 -> 알림&현재 알림 허용 여부로 변경
- 알림 클릭시 어플의 알림 설정 화면으로 이동 -> 사용자가 직접 어플 권한 알림 ON/OFF 할 수 있도록 수정
- 에러 발생했을 때 토스트 메시지 보여줌
- 일정 상세화면, 친구 조회 및 추가, 검색, 로그인 화면에 토스트 추가
- 검색 결과 없으면 화면에 "검색 결과가 없습니다" 보여주도록 TextView 추가
- SettingFragment -> onViewCreated 내부 클릭리스너, flow 관련 동작 함수로 분리
> [K020] notification 앱 설정 화면 이동 및 토스트 메시지 추가

- be/src/friend/friend.controller.ts
- be/src/friend/friend.service.ts
> [J033] 자기 자신을 친구 추가 했을 경우 추가

- be/src/schedule-api/schedule-api.service.ts
> [J033] 오류 수정

- be/docker-compose.yml
- be/src/friend/friend.service.ts
- be/src/push/push.service.ts
- be/src/schedule-api/schedule-api.service.ts
> [J033] fix push

- be/src/push/push.service.ts
> [J033] fix push message

- PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapter.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/adapter/ScheduleAdapterViewHolder.kt
- PlanJ/app/src/main/java/com/boostcamp/planj/ui/search/SearchActivity.kt
- PlanJ/app/src/main/res/layout/fragment_setting_fail.xml
- PlanJ/app/src/main/res/layout/fragment_sign_in.xml
- PlanJ/app/src/main/res/layout/fragment_sign_up.xml
- PlanJ/app/src/main/res/layout/item_schedule.xml
- 로그인/회원가입 -> NestedScrollView를 이용해 스크롤 가능하도록 함
- 완료한 일정 다시 미완료로 변경이 안된다는 피드백 -> 다시 변경 가능하도록 이전처럼 라디오버튼 형태로 변경
> [K020] 로그인/회원가입 스크롤, item_schedule 라디오버튼형태로 변경

- be/src/main.ts
- be/src/schedule-api/schedule-api.service.ts
- be/src/utils/middleware/disable-connection.global.ts
- be/src/utils/middleware/set-connection-header.middleware.ts
- be/src/utils/middleware/shut-down.ts
> [J033] 공유 일정 삭제 문제 수정

- be/src/push/push.service.ts
> [J033] 알람 부분 버그 수정
